### PR TITLE
Fix jest.config.json

### PR DESCRIPTION
**Pull request by yohav**
Bad json format

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thank you for trying to help, but this file is actually just a template and is used to generate the other jest configs in exercises and exercises-final. 

You can learn more about this by reading about [split-guide](http://npm.im/split-guide). Thanks!

**Comment by yohav** [comment]
But I got an exception. The JSON can't been parsed. You are missing the ',
character. And you have comments inside the JSON.
What I am missing?

בתאריך שבת, 17 בדצמ׳ 2016 ב-17:36 מאת Kent C. Dodds <
notifications@github.com>:

**Comment by kentcdodds** [comment]
You shouldn't be trying to parse that file. Why are you trying to?

**Comment by yohav** [comment]
When you run "npm run setup", it fails in the "npm run validate" phase.
The exception is:
Error: Jest: Failed to parse config file
D:\Projects\react-jest-workshop\exercises-final\jest.config.json.
    at parse
(D:\Projects\react-jest-workshop\node_modules\jest-config\build\loadFromFile.js:22:15)
    at promisify.then.data
(D:\Projects\react-jest-workshop\node_modules\jest-config\build\loadFromFile.js:26:20)

And the reason is that the validate phase runs "npm run generate -s" which
runs "split-guide generate" that takes the bad JSON from the templates
directory and put it in the exercises and exercises-final directoris.

2016-12-17 17:39 GMT+02:00 Kent C. Dodds <notifications@github.com>:

**Comment by kentcdodds** [comment]
Hmmmm.... I don't experience this myself. What does the resulting config look like in your exercises-final directory?

**Comment by yohav** [comment]
{
  "testPathDirs": [
    // WORKSHOP_START
    "exercises"
    // WORKSHOP_END
    // FINAL_START
    "exercises-final"
    // FINAL_END
  ],
  "coverageThreshold": {
    "global": {
      "branches": 100,
      "functions": 95,
      "lines": 100,
      "statements": 100
    }
  }
}


2016-12-17 17:50 GMT+02:00 Kent C. Dodds <notifications@github.com>:

**Comment by kentcdodds** [comment]
That's odd... Seems like a split-guide bug. Care to dig in and figure out the problem?

**Comment by yohav** [comment]
Why do you think it is a split-guide problem?
It seems that it copys the jest.config.json from the templates dir to the
exercises-final dir.
Then, the "validate" phase runs "npm run test:final -s" which cause the
eception because of the bad JSON.
As I see it, the bug is in the jest.config.json which isn't parsable.

2016-12-17 17:57 GMT+02:00 Kent C. Dodds <notifications@github.com>:

**Comment by kentcdodds** [comment]
But it's not supposed to simply copy it. It's supposed to alter it based on those lines. That's the bug.

**Comment by yohav** [comment]
Oh I understand. I didn't know this lib before. I will try to investigate
the problem.

בתאריך שבת, 17 בדצמ׳ 2016 ב-18:27 מאת Kent C. Dodds <
notifications@github.com>:

**Pull request closed without merging**
